services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: .
    command: pnpm run dev
    env_file: .env
    volumes:
      - .:/app/:cached
    depends_on:
      - postgres
    ports:
      - '5173:5173'

volumes:
  postgres:
