services:
  postgres:
    image: postgres:17-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: .
    command: pnpm run dev
    env_file: .env
    volumes:
      - .:/app/:cached
      - ./.mkcert/:/root/.vite-plugin-mkcert/
    depends_on:
      - postgres
    ports:
      - '5173:5173'

  app-prod:
    image: flippr:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/flippr_production
    volumes:
      - uploads:/app/public/uploads/
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  postgres:
  uploads:
